[build]
  command = "bash scripts/build_on_netlify.sh"
  publish = "dist/"

[build.environment]
  PYTHON_VERSION = "3.10.12"
  MISE_PYTHON_GITHUB_ATTESTATIONS = "false"
  NODE_VERSION = "18"
  INSTALL = "1"
  UPDATE_CONTENT = "1"
  BUILD = "1"
