name: Build and Deploy

on:
  workflow_dispatch: # This adds a manual trigger
  push:
    branches:
      - main
#  pull_request:
#    branches:
#      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact_name: ${{ steps.set_artifact_name.outputs.name }}
    steps:
      - name: Set current date as env variable
        id: set_artifact_name
        run: |
          echo "DATE_NOW=$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_ENV
          echo "name=dist-$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_OUTPUT
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          lfs: 'true'
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.12'
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Build the JupyterLite with Extension(s)
        shell: bash
        run: |
          npm run build
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ env.DATE_NOW }}
          path: ./dist

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  preview:
    needs: build
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.artifact_name }}
          path: ./dist
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: './dist'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy Preview for PR #${{ github.event.number }}"
          enable-pull-request-comment: true
          enable-commit-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
